schedule: "0 0 * * *" # every day at 00:00
createNamespace: true
image: ghcr.io/socialgouv/infra-as-loop:latest
mountSecrets:
  - name: keys-of-the-kingdom
resources:
  limits:
    cpu: "2"
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 512Mi
component: 
suspend: true
files: {}
#   snip.jsonnet: |
